Controllers/LoginController.cs
using BeautySaloon.Models;
using BeautySaloon.Repositoryes.Login;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace BeautySaloon.Controllers
{
	public class LoginController : Controller
	{
		private readonly ILoginRepository _loginRepository;

		public LoginController(ILoginRepository loginRepository)
		{
			_loginRepository = loginRepository;
		}
		// GET: LoginController
		public ActionResult Index()
		{
			return View();
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Index(LoginModel model)
		{
			if (ModelState.IsValid)
			{
				User? user = await _loginRepository.GetUserByEmailAndPasswordAsync(model.Email, model.Password);
				if (user != null)
				{
					await Authenticate(user);

					return RedirectToAction("Index", "Home");
				}
				ModelState.AddModelError("", "Некорректные логин и(или) пароль");
			}
			return View(model);
		}
		private async Task Authenticate(User user)
		{

			var claims = new List<Claim>
	{
		new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
		new Claim(ClaimTypes.GivenName, user.Name),
		new Claim(ClaimTypes.Email, user.Email),
		new Claim(ClaimTypes.MobilePhone, user.PhoneNumber ?? "")
	};

			ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType,
				ClaimsIdentity.DefaultRoleClaimType);

			await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
			return RedirectToAction("Index", "Home");
		}
	}
}

Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using BeautySaloon.Models;
using BeautySaloon.Repositoryes.Search;

namespace BeautySaloon.Controllers
{
	public class SearchController : Controller
	{
		private readonly ISearchRepository _searchRepository;

		public SearchController(ISearchRepository searchRepository)
		{
			_searchRepository = searchRepository;
		}

		public async Task<IActionResult> Index()
		{
			ViewBag.State = true;
			var services = await _searchRepository.GetServices();
			var service = await _searchRepository.GetService();
			var model = new ViewModel { Service = service, Services = services };
            ViewData["State"] = ViewBag.State;
            return View(model);
		}

		public async Task<IActionResult> Search(string searchString)
		{
           

            var services = await _searchRepository.Search(searchString);
			return PartialView("SearchResult", services);
		}
	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"]  Accent</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/MainPage.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/PartialView.css" asp-append-version="true" />




	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/BeautySaloon.styles.css" asp-append-version="true" />
	<link href="https://fonts.googleapis.com/css2?family=Forum&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&family=Forum&display=swap" rel="stylesheet">
</head>

<body>
	<style>
		header .container {
			display: flex;
			align-items: center;
		}

		header .row {
			flex-wrap: nowrap;
			width: 100%;
		}


		/* Стили для логотипа */
		header .logo {
			min-width: 100%;
			height: auto ;
		}

		/* Стили для контактной информации */
		header .text-light p {
			margin-bottom: 0;
		}

		/* Стили для кнопок */
		header .button-color {
			margin-left: 10px;
		}

		/* Дополнительные стили для лучшего выравнивания */
		header .navbar-nav {
			display: flex;
			justify-content: space-around;
			width: 100%;
		}

		.sticky-top {
			position: sticky;
			top: 0;
			z-index: 1030;
		}

		.navbar {
			padding: 0.5rem 1rem;
		}



		.text-light {
			color: #fff !important;
		}

		.me-4 {
			margin-right: 1.5rem !important;
		}

		.me-1 {
			margin-right: 0.25rem !important;
		}

		.btn-outline-light {
			color: #fff;
			border-color: #fff;
		}

			.btn-outline-light:hover {
				color: #000;
				background-color: #fff;
				border-color: #fff;
			}

		.underline {
			text-decoration-color: #d19a66;
		}

		.text-color {
			color: #d19a66;
		}

			.text-color:hover {
				color: #fff;
			}
	
	</style>
	
	
	
	<div class="content-wrapper">
		<header>
			<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
				<div class="container-fluid">
					<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span> 
					</button>
					<div class="collapse navbar-collapse" id="ftco-nav">
						<ul class="navbar-nav">
							<li class="nav-item active">
								<div class="container-fluid bg-dark justify-content-between align-items-center w-25 ms-lg-5 me-5">
									<a class="navbar-brand" href="@Url.Action("Index", "Home")">
										<img src="https://static.tildacdn.com/tild6465-6432-4263-a332-313565363232/logo.png" class="logo" alt="Логотип">
									</a>
								</div>
							</li>
							<li class="nav-item">
								<div class=" text-light d-flex align-items-center ms-5 me-5 pt-3 menu-button">
									<img class="me-1" src="https://static.tildacdn.com/tild3837-6461-4262-a136-643661653262/photo.svg" />
									<p class="mb-0">г.Барнаул, Ленина, 1А</p>
								</div>
							</li>
							<li class="nav-item">
								<div class="text-light d-flex align-items-center ms-5 me-5 pt-3 menu-button">
									<img class="me-1" src="https://static.tildacdn.com/tild6366-3938-4233-a263-353962623137/photo.svg" />
									<p class="mb-0">+7-912-345-67-89</p>
								</div>
							</li>
							<li class="nav-item">
								<div class="me-4 pt-3 menu-button">
									<a href="#" class="underline" data-bs-toggle="modal" data-bs-target="#myModal"><p class="text-color">Заказать звонок</p></a>
								</div>
							</li>

							<li class="nav-item">
								<a class="nav-link " href="@Url.Action("Index", "Search")">
									<button class="btn btn-outline-dark text-light button-color menu-button">Онлайн запись</button>
								</a>
							</li>

							<li class="nav-item">
								@if (User?.Identity?.IsAuthenticated == true)
								{
									<a class="nav-link justify-content-end " href="@Url.Action("Index", "Account")">
										<button class="btn btn-outline-dark text-light button-color menu-button">Личный кабинет</button>
									</a>
								}
								else
								{
									<a class="nav-link justify-content-end " href="@Url.Action("Index", "Login")">
										<button class="btn btn-outline-dark text-light button-color menu-button">Войти</button>
									</a>
								}
							</li>

						</ul>
					</div>
				</div>
			</nav>
		</header>

		<main role="main" class="bg-dark">
			@RenderBody()
		</main>
	</div>
	<footer class="sticky-bottom footer text-muted mt-5">
		<nav class="footer-content navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark  box-shadow mb-0">
			<div class="container bg-dark justify-content-between ">
				<div class="row align-items-center d-flex w-100 ">
					<div class="col-lg-4 ps-5">
						<img src="https://static.tildacdn.com/tild3164-3238-4265-b361-366364393936/logo.svg" class="logo img-fluid" alt="Логотип">
					</div>
					<div class="d-flex col-lg-4 text-center text-light w-50">
						<img class="me-1" src="https://static.tildacdn.com/tild3837-6461-4262-a136-643661653262/photo.svg" />
						<div class="pt-3 me-5">
							<p>г.Барнаул, Ленина, 1А</p>
						</div>
						<img class="me-1" src="https://static.tildacdn.com/tild6366-3938-4233-a263-353962623137/photo.svg" />
						<div class="pt-3">
							<p>+7 912 345 67 89</p>

						</div>
						<div class="ms-5 pt-3">
							<a href="#" class="underline" data-bs-toggle="modal" data-bs-target="#myModal"><p class="text-color">Заказать звонок</p></a>
						</div>
					</div>
					<div class="d-flex col-lg-4 text-end text-light w-auto">
						<a class="nav-link" href="@Url.Action("Index", "Search")">
							<button class="btn btn btn-outline-dark text-light button-color" type="submit">Онлайн запись</button>
						</a>
					</div>

				</div>
			</div>
		</nav>

		<div class="footer-simple bg-dark d-block d-lg-none text-center text-light">
			&copy; 2024 - Accent - <a asp-area="" asp-controller="Home" asp-action="Index" class="text-white"></a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>



<style>
	.modal-window {
		background-color: #da9471;
		margin-top: 20%;
		height: 70%;
		width: 100%;
		font-family: 'Forum',Arial,sans-serif;
	}

	.h {
		height: 80%;
	}

	.modal-window:hover {
		border: none;
	}

	.window-input {
		border: 2px solid #fff;
		margin-bottom: 5%;
		background-color: #da9471;
		height: 20%;
		border-radius: 4px;
		outline: none;
	}

	.window-button {
		height: 20%;
	}
</style>
<div class="modal fade " id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog h">
		<div class="modal-content modal-window">
			<div class="modal-header">
				<h5 class="modal-title ms-5 ps-3 mt-2" id="exampleModalLabel">Оставьте заявку и мы вам перезвоним</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<input type="text" id="nameInput" placeholder="Имя" class="w-100 window-input" />
				<div id="nameInputError" class="text-danger" style="display: none;">Поле "имя" не может быть пустым</div>

				<br />
				<input type="text" id="phoneInput" placeholder="Телефон" class="w-100 window-input" />
				<div id="phoneInputError" class="text-danger" style="display: none;">Поле "телефон" не может быть пустым</div>

				<div id="phoneCorrectlytError" class="text-danger" style="display: none;">Некоректно введен телефон</div>

				<br />
				<button id="submitBtn" class="w-100 mt-3 window-button">Оставить заявку</button>

			</div>
			<div class="modal-footer">
				<p>*Ваши данные в безопасности и не будут переданы третьим лицам</p>
			</div>
		</div>
	</div>
</div>
<script src="~/js/site.js"></script>