Controllers/LoginController.cs
using BeautySaloon.Models;
using BeautySaloon.Repositoryes.Login;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace BeautySaloon.Controllers
{
	public class LoginController : Controller
	{
		private readonly ILoginRepository _loginRepository;

		public LoginController(ILoginRepository loginRepository)
		{
			_loginRepository = loginRepository;
		}
		// GET: LoginController
		public ActionResult Index()
		{
			return View();
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Index(LoginModel model)
		{
			if (ModelState.IsValid)
			{
				User? user = await _loginRepository.GetUserByEmailAndPasswordAsync(model.Email, model.Password);
				if (user != null)
				{
					await Authenticate(user);

					return RedirectToAction("Index", "Home");
				}
				ModelState.AddModelError("", "Некорректные логин и(или) пароль");
			}
			return View(model);
		}
		private async Task Authenticate(User user)
		{

			var claims = new List<Claim>
	{
		new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
		new Claim(ClaimTypes.GivenName, user.Name),
		new Claim(ClaimTypes.Email, user.Email),
		new Claim(ClaimTypes.MobilePhone, user.PhoneNumber ?? "")
	};

			ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType,
				ClaimsIdentity.DefaultRoleClaimType);

			await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
			return RedirectToAction("Index", "Home");
		}
	}
}

Controllers/RegistrationController.cs
using BeautySaloon.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Security.Claims;
using BeautySaloon.Repositoryes.Registration;

namespace BeautySaloon.Controllers
{
    public class RegistrationController : Controller
    {
		private readonly IRegistrationRepository _registrationRepository;

		public RegistrationController(IRegistrationRepository registrationRepository)
		{
			_registrationRepository = registrationRepository;
		}
		public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(RegisterationModel model)
        {
            if (ModelState.IsValid)
            {
				User? user = await _registrationRepository.GetUserByEmailAsync(model.Email);
				if (user == null)
                {
                    // добавляем пользователя в бд
                    user = new User { Email = model.Email, Password = model.Password, PhoneNumber = model.PhoneNumber, Name = model.Name };



					await _registrationRepository.AddUserAsync(user);


					await Authenticate(user); // аутентификация

                    return RedirectToAction("Index", "Home");
                }
                else
                    ModelState.AddModelError("", "Некорректные логин и(или) пароль");
            }
            return View(model);

        }
        private async Task Authenticate(User user)
        {

			var claims = new List<Claim>
	{
		new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
		new Claim(ClaimTypes.GivenName, user.Name),
		new Claim(ClaimTypes.Email, user.Email),
		new Claim(ClaimTypes.MobilePhone, user.PhoneNumber ?? "")
	};


			ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType,
                ClaimsIdentity.DefaultRoleClaimType);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));

        }
    }
}

Views/Login/Index.cshtml
@model LoginModel

@{
	ViewData["Title"] = "";
	Layout = null;
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link rel="stylesheet" href="~/css/LoginAndRegistration.css" asp-append-version="true" />

<body class="bg-dark">
<div class="container d-flex justify-content-center align-items-center mt-5">
	<div class="container-fluid">

		<div class="col-md-4 offset-md-4">
			<div class="form-container">
				<div class="form-icon mt-2"><i class="fa fa-user"></i></div>
				<h3 class="title">Login</h3>
				
					<form class="form-horizontal" asp-action="Index" asp-controller="Login" asp-anti-forgery="true">
						<div class="validation" asp-validation-summary="ModelOnly"></div>
						<div>
							<div class="form-group">
								<label asp-for="Email">Введите Email</label>
								<input class="form-control" type="email" asp-for="Email" />
								<span asp-validation-for="Email" />
							</div>
							<div class="form-group">
								<label asp-for="Password">Введите пароль</label>
								<input class="form-control"  asp-for="Password" />
								<span asp-validation-for="Password" />
							</div>
							<div class="form-group">
								<input type="submit" value="Войти" class="btn btn-default" />
							</div>
							<div class="text-center mt-3">

								<a href="#" class="text-decoration-none" data-toggle="modal" data-target="#forgotPasswordModal">Забыли пароль?</a>
							</div>

							</div>
							<div class="text-center mt-2">
								<p>Нет аккаунта? <a href="@Url.Action("Index", "Registration")" class="text-decoration-none ">Зарегистрироваться</a></p>
							
						</div>
					</form>
			</div>
		</div>

	</div>
</div> 
</body>
<!-- Модальное окно -->
<div class="modal fade" id="forgotPasswordModal" tabindex="-1" role="dialog" aria-labelledby="forgotPasswordModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="forgotPasswordModalLabel">Восстановление пароля</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form id="forgotPasswordForm">
					<div class="form-group">
						<label for="email">Email адрес</label>
						<input type="email" class="form-control" id="email" name="email" required>
					</div>
					<button type="submit" class="btn btn-primary">Подтвердить</button>
				</form>
			</div>
		</div>
	</div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
	$(document).ready(function () {
		// При нажатии на ссылку "Забыли пароль?" открываем модальное окно
		$('a[href="#"]').click(function () {
			$('#forgotPasswordModal').modal('show'); // Открываем модальное окно
		});

		// Обработка отправки формы в модальном окне
		$('#forgotPasswordForm').submit(function (event) {
			event.preventDefault(); // Предотвращаем стандартное действие формы

			// Получаем значение email из поля формы
			var email = $('#email').val();

			// Ваша логика отправки данных на сервер или обработки здесь
			console.log('Email адрес для восстановления пароля:', email);

			// Дополнительные действия (например, закрытие модального окна)
			$('#forgotPasswordModal').modal('hide');
		});
	});
</script>